travis:
  secure:
    BINSTAR_TOKEN: gndjGj0jGimtkt1eFMk5kSE7Zn59xdMZwZungFBDjGgAG9omT7bjz/gUe8n7XLanm8qwk1E0qj9vXYidavmckW5RDTM9EwU6vT+l3Xl6yNXF2A1dmuiwQNPjZcP6kp3y/D86LOIvjhNtt0WutTpWEt3SM0w9nkS+h2BW5keyUS0PS0zO4iSkOL9FNU/9LWm541HGk/IaMqNK3zeXYNOtal5RoZmgJ/4roDM8sWBDpKzSplUxFEtARnJCIltLNi93NmxMoe9uudOJ9BsOFpa/n3/VaKYrUQwSX/j8kqQoqo3KN1WT0I0IuLDY2XrwfJ6zHPwlx6yZQ973a1WoYLFII9szl6sifTxaXd5VMRCWwSwKjxAnYY3+v04wfXJSB95CUyY5Upwj1xj2cA7s4B5kc2KBrYkIud6S3UeHnQ+GVzRtOK7es3UOon0Eljl91JM8uVVqXS/UtvzIF4vwLgenU1aCQuWxaVzOsbUu644q/keNQOR5+U4fPDSqOech5UJiKMJwMCrOMYKfTD/7btJ6Nmk1vFXJVJH1xW5rBBWc5h8QfvAIP7Rpw9Xck96d7qUdLfjlEQfs0iWgVDxJQBC1nq31IGeqcv9RzeZlaoL49ebpVaUyPlTHEcfWdjLyimSMUq8n34f8S/ceHO0lF7miqVe+2tOEsqJSUzEWpyeEdb4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
