travis:
  secure:
    BINSTAR_TOKEN: b+afGZqt81PBWtcLXILufa8QzUKn8Hoev0ZEvsisLOh/iL7Vund7hnn6Q4dmZe5YiqdrCYtxOMNT1mCZwEnyEseck3rpiI7grWMPrw6lc4nse/x85FlNtENlqoYJyLhRWiJJ0sd0CjMCa+i4i0he8KeBU2IRXcZT1Y52XFIw9CcUdFnQFBvNR1lUxZB6dTrIEmHOv1bCx8i/cdUP8nnRAZNzwBupG37R1H+inrjxMgzNOWUVBIOhx+I52/GZ6civvgLksy/+D8PsqJgZOivicuF2NGZN739rUD3SP/phFwRdzhJyWW6X56q5irDMgGceJMLB9vMj5+/xStNIiHGzqOdzBSOib7kko5kR5qtfa+p6qZdf7/G1jevS1mY4uEXQDhOtCPGioXy1wAuh3MWhHT5ZHd0YNxWqW+I3Io1+UETNAwAvLVht2TKiOkW/D06lmiqK65Wn3EeCW3cNKv+MSM7t97EGuGfpXJdxyE5Bp6qZJNxY/X4breL15VH8i4wW3R0gZ1OHhh0RUkT9zzMPL5juG4fqkgKxa94/1tK32+o3lNxj5oFxSSSbdEgCJdCR9+2J14p2tjgDW6VhErmLTnWXdpsTNK1PADteCysP9cwoy1BMQDWFD6tAT+7beUfvElfHg56q5Xmv5j9s+ThvsMlfLXLAPinJ/AZo5EhuR28=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
